version: "3"
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PASSWORD=abc123
      - PYTHONDONTWRITEBYTECODE=1
      - ENSO_URL=https://psl.noaa.gov/enso/mei/data/meiv2.data
      - WAIT_HOSTS=postgres:5432
    volumes:
      - ./src:/src
      - ./tests:/tests
    ports:
      - "80:80"


  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=ensoserver
      - POSTGRES_PASSWORD=abc123
    ports:
      - "5432:5432"