name: e2e-tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: docker-compose build
      - name: Docker Up
        run: docker-compose up -d app
      - name: E2E Tests
        run: docker-compose run --rm --no-deps --entrypoint=pytest app /tests/e2e -v
